"""empty message

Revision ID: 68ce29af74ce
Revises: dbb0efdd4b8b
Create Date: 2024-11-01 18:12:32.426115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ce29af74ce'
down_revision = 'dbb0efdd4b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('term', sa.Integer(), nullable=False))
        batch_op.drop_column('total_term')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('total_terms')

    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('term_number', sa.Integer(), nullable=True))
        batch_op.drop_column('term_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('term_name', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('term_number')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_terms', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('fee_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_term', sa.INTEGER(), nullable=False))
        batch_op.drop_column('term')

    # ### end Alembic commands ###
