"""Initial migration

Revision ID: d5309a00b0b8
Revises: 
Create Date: 2024-11-01 17:03:47.307052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5309a00b0b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('term')
    op.drop_table('fee_structure')
    op.drop_table('fee_payment')
    op.drop_table('expense')
    op.drop_table('student')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('total_fee',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('total_fee',
               existing_type=sa.FLOAT(),
               nullable=True)

    op.create_table('student',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('roll_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=15), nullable=True),
    sa.Column('branch', sa.VARCHAR(length=50), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('dob', sa.DATE(), nullable=True),
    sa.Column('joining_year', sa.INTEGER(), nullable=True),
    sa.Column('leaving_year', sa.INTEGER(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('total_fee', sa.FLOAT(), nullable=True),
    sa.Column('terms', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roll_number')
    )
    op.create_table('expense',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fee_payment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('term', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fee_structure',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('branch', sa.VARCHAR(length=50), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('term',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('term_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('cleared', sa.BOOLEAN(), nullable=True),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
