"""Renamed terms to total_terms

Revision ID: dbb0efdd4b8b
Revises: fd242cc04b51
Create Date: 2024-11-01 17:45:00.815962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb0efdd4b8b'
down_revision = 'fd242cc04b51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_term', sa.Integer(), nullable=False))
        batch_op.drop_column('term')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('term', sa.INTEGER(), nullable=False))
        batch_op.drop_column('total_term')

    # ### end Alembic commands ###
