"""Add terms relationship to Student

Revision ID: fd242cc04b51
Revises: d5309a00b0b8
Create Date: 2024-11-01 17:20:04.302554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd242cc04b51'
down_revision = 'd5309a00b0b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_terms', sa.Integer(), nullable=False))

    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('term_name', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.drop_column('term_name')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('total_terms')

    # ### end Alembic commands ###
